<div style='text-align:center;'>
  <img src="CDAM.PNG" width="1200">
</div>

<div style="text-align: center; font-weight: bold; font-size: 22px; color: #1a1a1a;">
  <div style="color: #0B5394; font-size: 38px;">CENTER FOR DATA ANALYTICS AND MODELLING (CDAM)</div>
  <div style="color: #38761D; font-size: 24px;">DATA CLEANING AND MANIPULATION</div>
  <br>
  <div style="color: #CC0000; font-size: 22px;">FACILITATOR:</div>
  <div style="color: #000000; font-size: 20px;">VICTOR WANDERA LUMUMBA</div>
  <div style="color: #3D85C6; font-size: 20px;">Chuka University, Kenya</div>
  <br>
  <div style="color: #6AA84F; font-size: 18px;">Date:</div>
  <div style="color: #351C75; font-size: 18px;">February 16, 2026</div>
</div>

## **DATA IMPORTATION, CLEANING, WRANGLING AND MANIPULATION**

#### **Objectives**
- Import and Inspect Real World Data Set
- Identify and Handle Missing values, Duplicates and Outliers
- Subset and Filter Rows Based on Some Conditions
- Selecting Specific Columns
- Data Engineering (Creating a Categorical Variables From Continous Variables)
- Generate Comprehensive Descriptive Statistics

## **1. Data Importation**
**Why Does this Matter**
- CSV File is a Universal Standard Tabular Data Structure
- Pandas Function read_csv() makes it possible to read csv File from the Local Directory
- The Function read_csv() helps prevent downstream errors.

### **Install the Following Libraries if not Installed**

In [ ]:
# pip install pandas
# pip install numpy
# pip install seaborn
# pip install matplotlib

### **Load the Required Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

#### **Read the Dataset**

In [3]:
df = pd.read_csv("GSSsubset1.csv")
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,NaN,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,NaN,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0

### **General Inspection of the Data**

In [31]:
### Column Names
print(f"Columns:{df.columns.tolist()}")

Columns:['id', 'sex', 'degree', 'income', 'marital', 'age', 'height', 'weight', 'hrswrk']

In [32]:
### Dimension of the Data
print(f"Shape: {df.shape}")

Shape: (3000, 9)

In [33]:
#### Variable Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   object
 2   degree   2942 non-null   object
 3   income   2767 non-null   float64
 4   marital  2934 non-null   object
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   2879 non-null   float64
 8   hrswrk   2933 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 211.1+ KB

### **General Descriptive Statistics**

In [34]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'age',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'height',
 'hist',
 'hrswrk',
 'iat',
 'id',
 'idxmax',
 'idxmin',
 'iloc',
 'income',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'marital',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'sex',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'weight',
 'where',
 'xs']

In [35]:
df.describe()

,id,income,age,height,weight,hrswrk
count,3000.000000,2767.000000,3000.000000,3000.000000,2879.000000,2933.000000
mean,1500.500000,63871.815790,42.078000,67.400500,76.389232,39.778043
std,866.169729,51634.075898,13.314316,3.641297,14.584233,12.594723
min,1.000000,3720.040000,18.000000,58.100000,45.000000,0.000000
25%,750.750000,31989.025000,33.000000,64.600000,65.800000,34.000000
50%,1500.500000,49586.540000,42.000000,67.200000,75.700000,41.000000
75%,2250.250000,78986.595000,51.000000,70.100000,85.700000,48.000000
max,3000.000000,609741.180000,80.000000,78.600000,120.000000,79.000000

In [36]:
df.drop(columns = ["id"]).describe()

              income          age       height       weight       hrswrk
count    2767.000000  3000.000000  3000.000000  2879.000000  2933.000000
mean    63871.815790    42.078000    67.400500    76.389232    39.778043
std     51634.075898    13.314316     3.641297    14.584233    12.594723
min      3720.040000    18.000000    58.100000    45.000000     0.000000
25%     31989.025000    33.000000    64.600000    65.800000    34.000000
50%     49586.540000    42.000000    67.200000    75.700000    41.000000
75%     78986.595000    51.000000    70.100000    85.700000    48.000000
max    609741.180000    80.000000    78.600000   120.000000    79.000000

### **Frequencies for Categorical Variables**

In [37]:
print("Educational Level Distribution")
df['degree'].value_counts()

Educational Level Distribution

degree
HIGH SCHOOL       1094
LT HIGH SCHOOL     583
BACHELOR           566
JUNIOR COLLEGE     465
GRADUATE           234
Name: count, dtype: int64

In [38]:
print("Marital Status Distribution")
df['marital'].value_counts()

Marital Status Distribution

marital
MARRIED          1518
NEVER MARRIED     691
DIVORCED          382
WIDOWED           227
SEPARATED         116
Name: count, dtype: int64

In [39]:
print("Gender Distribution")
df['sex'].value_counts()

Gender Distribution

sex
FEMALE    1563
MALE      1437
Name: count, dtype: int64

### **3. DATA CLEANING**

#### **3.1. Handling Missing Values**

In [40]:
#### Check the Presence of Missing Values
print("The Total Number of Missing Values per Variable")
print(df.isna().sum())

The Total Number of Missing Values per Variable
id           0
sex          0
degree      58
income     233
marital     66
age          0
height       0
weight     121
hrswrk      67
dtype: int64

In [41]:
### Present the Missing Values as Percentage of Total Data Points
print("Percentages of Missing Values")
Missing_value = df.isna().mean().round(4)*100
Missing_value

Percentages of Missing Values

id         0.00
sex        0.00
degree     1.93
income     7.77
marital    2.20
age        0.00
height     0.00
weight     4.03
hrswrk     2.23
dtype: float64

#### **Methods of Handling Missing Values**
- Complete Cases Analysis - Commonly used but risky
- Mean Imputation - For Symmetric Distributed Data
- Median Imputation - For Skewed Data (skewed left or right)
- Model Imputation - For Categorical Variables

#### **Complete Cases Analysis**

In [42]:
df_drop_all = df.dropna()
print(df_drop_all.isna().sum())

id         0
sex        0
degree     0
income     0
marital    0
age        0
height     0
weight     0
hrswrk     0
dtype: int64

In [43]:
df_drop_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2503 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2503 non-null   int64
 1   sex      2503 non-null   object
 2   degree   2503 non-null   object
 3   income   2503 non-null   float64
 4   marital  2503 non-null   object
 5   age      2503 non-null   int64
 6   height   2503 non-null   float64
 7   weight   2503 non-null   float64
 8   hrswrk   2503 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 195.5+ KB

### **Imputation Approach**
#### **Mean Imputation**

In [44]:
df.isna().sum()

id           0
sex          0
degree      58
income     233
marital     66
age          0
height       0
weight     121
hrswrk      67
dtype: int64

In [45]:
## Identify the Numeric Columns
numeric_cols = df.select_dtypes(include = 'number').columns

## Find the Median and Impute the Missing Values for the Numeric Columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

## Find the Mean and Impute the Missing Values for the Numeric Columns
# df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

### **Confirm the Imputation of Missing Values**

In [46]:
df.isna().sum()

id          0
sex         0
degree     58
income      0
marital    66
age         0
height      0
weight      0
hrswrk      0
dtype: int64

#### **Mode Imputation for the Missing values**

In [47]:
cat_cols = df.select_dtypes(include = ['object','category']).columns
for col in cat_cols:
    mode_val = df[col].mode()
    if not mode_val.empty:
        df[col] = df[col].fillna(mode_val[0])

In [48]:
df.isna().sum()

id         0
sex        0
degree     0
income     0
marital    0
age        0
height     0
weight     0
hrswrk     0
dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   object
 2   degree   3000 non-null   object
 3   income   3000 non-null   float64
 4   marital  3000 non-null   object
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   3000 non-null   float64
 8   hrswrk   3000 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 211.1+ KB

### **Data Cleaning - Handling Duplicates**

In [50]:
dup_rows = df.duplicated().sum()
print(dup_rows)

0

#### **Drop Duplicated Rows if Available**

In [51]:
df_clean = df.drop_duplicates()
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3000 non-null   int64
 1   sex      3000 non-null   object
 2   degree   3000 non-null   object
 3   income   3000 non-null   float64
 4   marital  3000 non-null   object
 5   age      3000 non-null   int64
 6   height   3000 non-null   float64
 7   weight   3000 non-null   float64
 8   hrswrk   3000 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 211.1+ KB

### **Outliers Handling**

In [52]:
### Identify Numeric Columns (float and int)
numeric_cols = df.select_dtypes(include = ['float64','int64']).columns
for col in numeric_cols:
     Q1 = df[col].quantile(0.25)
     Q3 = df[col].quantile(0.75)
     IQR = Q3 - Q1
     lower_bound = Q1 - 1.5 * IQR
     upper_bound = Q3 + 1.5 * IQR

     outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
     #print(outliers)
     print(f"Columns '{col}': {len(outliers)} Outliers")

Columns 'id': 0 Outliers
Columns 'income': 201 Outliers
Columns 'age': 10 Outliers
Columns 'height': 2 Outliers
Columns 'weight': 32 Outliers
Columns 'hrswrk': 155 Outliers

In [53]:
numeric_cols = ['income', 'height', 'weight', 'hrswrk']
outlier_ids = {}
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    # store IDs (assuming 'id' column exists)
    outlier_ids[col] = outliers['id'].tolist()

    print(f"Column '{col}': {len(outliers)} outliers")
    print(outliers['id'].tolist())
    print("-"*50)

Column 'income': 201 outliers
[11, 36, 38, 73, 76, 87, 88, 102, 111, 112, 144, 146, 174, 200, 206, 211, 223, 227, 244, 275, 286, 289, 306, 326, 352, 359, 375, 381, 397, 404, 437, 455, 460, 493, 505, 519, 523, 536, 544, 549, 568, 591, 596, 603, 608, 660, 668, 727, 730, 731, 732, 761, 767, 786, 797, 808, 834, 840, 847, 913, 923, 931, 946, 975, 976, 981, 984, 1003, 1034, 1054, 1061, 1082, 1087, 1093, 1108, 1127, 1128, 1134, 1149, 1163, 1189, 1242, 1250, 1310, 1344, 1407, 1414, 1418, 1461, 1489, 1506, 1573, 1575, 1598, 1609, 1627, 1638, 1659, 1676, 1677, 1681, 1685, 1691, 1694, 1696, 1710, 1711, 1717, 1731, 1760, 1762, 1770, 1805, 1806, 1814, 1819, 1867, 1870, 1873, 1886, 1888, 1916, 1943, 1953, 1961, 1965, 2018, 2019, 2030, 2042, 2075, 2088, 2107, 2120, 2148, 2149, 2153, 2170, 2181, 2228, 2246, 2254, 2265, 2268, 2281, 2285, 2287, 2292, 2295, 2325, 2336, 2374, 2397, 2414, 2462, 2473, 2475, 2480, 2486, 2498, 2527, 2531, 2539, 2550, 2579, 2590, 2607, 2617, 2627, 2633, 2634, 2644, 2645, 2696, 2701, 2708, 2716, 2728, 2732, 2760, 2769, 2785, 2789, 2801, 2802, 2809, 2820, 2828, 2830, 2844, 2858, 2864, 2880, 2896, 2897, 2933, 2948, 2954, 2979, 2993, 2997]
--------------------------------------------------
Column 'height': 2 outliers
[257, 431]
--------------------------------------------------
Column 'weight': 32 outliers
[202, 222, 279, 326, 382, 451, 522, 523, 683, 708, 820, 958, 998, 1083, 1374, 1430, 1556, 1600, 1640, 1681, 1742, 1958, 2015, 2219, 2234, 2235, 2396, 2462, 2575, 2842, 2870, 2898]
--------------------------------------------------
Column 'hrswrk': 155 outliers
[39, 56, 63, 67, 72, 73, 106, 107, 115, 124, 208, 246, 250, 260, 278, 282, 305, 322, 378, 385, 387, 424, 426, 433, 437, 469, 479, 506, 535, 581, 585, 600, 602, 622, 658, 672, 694, 734, 736, 777, 780, 823, 848, 865, 936, 983, 996, 1029, 1057, 1087, 1129, 1150, 1194, 1196, 1197, 1223, 1229, 1248, 1274, 1287, 1302, 1305, 1316, 1335, 1345, 1350, 1386, 1388, 1406, 1426, 1429, 1439, 1450, 1466, 1568, 1571, 1585, 1612, 1624, 1627, 1682, 1731, 1739, 1742, 1756, 1762, 1769, 1790, 1792, 1799, 1803, 1819, 1822, 1832, 1879, 1884, 1891, 1894, 1898, 1902, 1944, 1992, 2019, 2071, 2130, 2178, 2237, 2239, 2265, 2272, 2300, 2317, 2333, 2337, 2343, 2352, 2370, 2413, 2419, 2448, 2470, 2505, 2522, 2524, 2532, 2534, 2538, 2549, 2550, 2555, 2568, 2569, 2607, 2629, 2640, 2649, 2664, 2684, 2685, 2689, 2707, 2721, 2732, 2748, 2796, 2851, 2854, 2901, 2917, 2946, 2951, 2958, 2968, 2981, 3000]
--------------------------------------------------

In [54]:
df.head(20)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18,73.2,86.3,35.0
1,2,MALE,HIGH SCHOOL,36544.91,MARRIED,35,69.9,95.3,47.0
2,3,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28,70.1,60.9,16.0
3,4,FEMALE,GRADUATE,49586.54,MARRIED,43,61.9,76.0,44.0
4,5,MALE,HIGH SCHOOL,48899.47,MARRIED,48,65.8,58.9,44.0
5,6,FEMALE,HIGH SCHOOL,47790.38,MARRIED,43,60.7,68.4,46.0
6,7,FEMALE,BACHELOR,102903.23,MARRIED,42,66.5,66.7,51.0
7,8,MALE,HIGH SCHOOL,36707.09,NEVER MARRIED,52,65.9,76.8,48.0
8,9,FEMALE,BACHELOR,48404.51,MARRIED,35,66.8,94.6,28.0
9,10,MALE,HIGH SCHOOL,29044.70,NEVER MARRIED,18,69.3,85.2,41.0
10,11,FEMALE,GRADUATE,419380.86,SEPARATED,58,62.4,64.8,31.0
11,12,MALE,JUNIOR COLLEGE,14995.63,WIDOWED,40,66.8,68.7,45.0
12,13,FEMALE,LT HIGH SCHOOL,22832.15,WIDOWED,52,61.3,61.0,25.0
13,14,MALE,LT HIGH SCHOOL,23183.92,MARRIED,50,71.6,100.4,55.0
14,15,FEMALE,GRADUATE,114886.28,MARRIED,40,64.1,75.5,42.0
15,16,FEMALE,BACHELOR,59232.59,MARRIED,51,62.9,72.9,20.0
16,17,MALE,BACHELOR,49586.54,NEVER MARRIED,24,69.3,84.9,50.0
17,18,FEMALE,HIGH SCHOOL,37509.86,SEPARATED,49,61.5,58.8,31.0
18,19,FEMALE,LT HIGH SCHOOL,20512.23,WIDOWED,60,59.0,62.9,22.0
19,20,FEMALE,BACHELOR,84696.68,DIVORCED,63,59.7,65.5,42.0

### **Capping the Outliers**

In [55]:
numeric_cols = df.select_dtypes(include = ['float64','int64']).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Cap the Outliers
    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

In [56]:
numeric_cols = df.select_dtypes(include = ['float64','int64']).columns
for col in numeric_cols:
     Q1 = df[col].quantile(0.25)
     Q3 = df[col].quantile(0.75)
     IQR = Q3 - Q1
     lower_bound = Q1 - 1.5 * IQR
     upper_bound = Q3 + 1.5 * IQR

     outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
     #print(outliers)
     print(f"Columns '{col}': {len(outliers)} Outliers")

Columns 'id': 0 Outliers
Columns 'income': 0 Outliers
Columns 'age': 0 Outliers
Columns 'height': 0 Outliers
Columns 'weight': 0 Outliers
Columns 'hrswrk': 0 Outliers

### **SAVE THE CLEAN DATA**

In [57]:
df.to_csv("Clean_GSSsubset.csv")

## **DATA MANIPULATION**
- Filtering (Rows Manipulation-subsetting rows)
- Selecting (Columns Selection)
- groupby
- Aggregating and Summarizing
- Combined Selection and Filtering

#### **Filtering**

In [58]:
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1.0,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18.0,73.2,86.3,35.0
1,2.0,MALE,HIGH SCHOOL,36544.91,MARRIED,35.0,69.9,95.3,47.0
2,3.0,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28.0,70.1,60.9,16.0
3,4.0,FEMALE,GRADUATE,49586.54,MARRIED,43.0,61.9,76.0,44.0
4,5.0,MALE,HIGH SCHOOL,48899.47,MARRIED,48.0,65.8,58.9,44.0

#### **Filter to have Male Participants Only**

In [59]:
male = df[df['sex'] =='MALE']
male.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1.0,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18.0,73.2,86.3,35.0
1,2.0,MALE,HIGH SCHOOL,36544.91,MARRIED,35.0,69.9,95.3,47.0
4,5.0,MALE,HIGH SCHOOL,48899.47,MARRIED,48.0,65.8,58.9,44.0
7,8.0,MALE,HIGH SCHOOL,36707.09,NEVER MARRIED,52.0,65.9,76.8,48.0
9,10.0,MALE,HIGH SCHOOL,29044.70,NEVER MARRIED,18.0,69.3,85.2,41.0

#### **Multiple Filtering**

In [60]:
subset = df[(df['sex'] == 'FEMALE') &
    (df['age'] > 35) &
    (df['marital'] == 'MARRIED')]
subset.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
3,4.0,FEMALE,GRADUATE,49586.54,MARRIED,43.0,61.9,76.0,44.0
5,6.0,FEMALE,HIGH SCHOOL,47790.38,MARRIED,43.0,60.7,68.4,46.0
6,7.0,FEMALE,BACHELOR,102903.23,MARRIED,42.0,66.5,66.7,51.0
14,15.0,FEMALE,GRADUATE,114886.28,MARRIED,40.0,64.1,75.5,42.0
15,16.0,FEMALE,BACHELOR,59232.59,MARRIED,51.0,62.9,72.9,20.0

#### **OR Condition**

In [61]:
high_educ = df[(df['degree'] == "BACHELOR") | (df['degree'] == "GRADUATE")]
high_educ.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
3,4.0,FEMALE,GRADUATE,49586.5400,MARRIED,43.0,61.9,76.0,44.0
6,7.0,FEMALE,BACHELOR,102903.2300,MARRIED,42.0,66.5,66.7,51.0
8,9.0,FEMALE,BACHELOR,48404.5100,MARRIED,35.0,66.8,94.6,28.0
10,11.0,FEMALE,GRADUATE,138753.5975,SEPARATED,58.0,62.4,64.8,31.0
14,15.0,FEMALE,GRADUATE,114886.2800,MARRIED,40.0,64.1,75.5,42.0

In [62]:
high_educ_married = df[(df['degree'] == "GRADUATE") | (df['degree'] == "BACHELOR")]
high_educ_married.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
3,4.0,FEMALE,GRADUATE,49586.5400,MARRIED,43.0,61.9,76.0,44.0
6,7.0,FEMALE,BACHELOR,102903.2300,MARRIED,42.0,66.5,66.7,51.0
8,9.0,FEMALE,BACHELOR,48404.5100,MARRIED,35.0,66.8,94.6,28.0
10,11.0,FEMALE,GRADUATE,138753.5975,SEPARATED,58.0,62.4,64.8,31.0
14,15.0,FEMALE,GRADUATE,114886.2800,MARRIED,40.0,64.1,75.5,42.0

#### **Selecting Columns**

In [63]:
### Select Single Column (Income Column)
income_column = df['income']
income_column.head()

0    26722.56
1    36544.91
2    59587.14
3    49586.54
4    48899.47
Name: income, dtype: float64

In [65]:
### Select Multiplee Columbs
cols = ['sex','age','income', 'marital','degree']
selected_columns = df[cols]
selected_columns.head()

      sex   age    income        marital       degree
0    MALE  18.0  26722.56  NEVER MARRIED  HIGH SCHOOL
1    MALE  35.0  36544.91        MARRIED  HIGH SCHOOL
2  FEMALE  28.0  59587.14       DIVORCED  HIGH SCHOOL
3  FEMALE  43.0  49586.54        MARRIED     GRADUATE
4    MALE  48.0  48899.47        MARRIED  HIGH SCHOOL

### **Dropping of Columns**

In [66]:
dropped_columns = df.drop(columns = ['id', 'height'])
dropped_columns.head()

      sex       degree    income        marital   age  weight  hrswrk
0    MALE  HIGH SCHOOL  26722.56  NEVER MARRIED  18.0    86.3    35.0
1    MALE  HIGH SCHOOL  36544.91        MARRIED  35.0    95.3    47.0
2  FEMALE  HIGH SCHOOL  59587.14       DIVORCED  28.0    60.9    16.0
3  FEMALE     GRADUATE  49586.54        MARRIED  43.0    76.0    44.0
4    MALE  HIGH SCHOOL  48899.47        MARRIED  48.0    58.9    44.0

In [73]:
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1.0,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18.0,73.2,86.3,35.0
1,2.0,MALE,HIGH SCHOOL,36544.91,MARRIED,35.0,69.9,95.3,47.0
2,3.0,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28.0,70.1,60.9,16.0
3,4.0,FEMALE,GRADUATE,49586.54,MARRIED,43.0,61.9,76.0,44.0
4,5.0,MALE,HIGH SCHOOL,48899.47,MARRIED,48.0,65.8,58.9,44.0

### **Grouping and Summarizing**
* Spliting data by categories
* Essential for Comparative Analysis (e.g income by gender, or degree)
* Work with single of multiple columns
* Suppprts aggregation functions: mean(), median(), count(), std()

In [80]:
print("="*60)
print("GROUPING BY $ AGGREGATION")
print("="*60)

# Groupe Income by Education Level
print("Mean Income by Educational Level")
income_by_educ = df.groupby('degree')['income'].mean().sort_values(ascending = False)
income_by_educ

============================================================
GROUPING BY $ AGGREGATION
============================================================
Mean Income by Educational Level

degree
GRADUATE          101312.290983
BACHELOR           79394.490040
JUNIOR COLLEGE     63991.209984
HIGH SCHOOL        50326.169965
LT HIGH SCHOOL     33619.183349
Name: income, dtype: float64

#### **Groupe Income by Marital Status**

In [77]:
print("="*60)
print("GROUPING BY $ AGGREGATION")
print("="*60)

# Groupe Income by Education Level
print("Mean Income by Marital Status")
income_by_marital = df.groupby('marital')['income'].mean().sort_values(ascending = False)
income_by_marital

============================================================
GROUPING BY $ AGGREGATION
============================================================
Mean Income by Marital Status

marital
MARRIED          62940.739291
WIDOWED          59930.869152
SEPARATED        58308.433211
DIVORCED         56700.688233
NEVER MARRIED    49566.023582
Name: income, dtype: float64

In [78]:
print("="*60)
print("GROUPING BY $ AGGREGATION")
print("="*60)

# Groupe Income by Education Level
print("Mean Income by Gender")
income_by_gender = df.groupby('sex')['income'].mean().sort_values(ascending = False)
income_by_gender

============================================================
GROUPING BY $ AGGREGATION
============================================================
Mean Income by Gender

sex
MALE      62533.651788
FEMALE    55096.061528
Name: income, dtype: float64

In [79]:
prop_f_m = (55096.061528/62533.651788)*100
prop_f_m

88.10625951413371

#### **Frequency Distribution for Categorical Variables**

In [82]:
print("Count by Marital Status")
marital_count = df['marital'].value_counts()
marital_count

Count by Marital Status

marital
MARRIED          1584
NEVER MARRIED     691
DIVORCED          382
WIDOWED           227
SEPARATED         116
Name: count, dtype: int64

### **Multiple Grouping by**

In [93]:
print("Mean Income by Gender AND Marital Status")
multiple_grouping = df.groupby(['sex','marital'])['income'].mean()
multiple_grouping

Mean Income by Gender AND Marital Status

sex     marital
FEMALE  DIVORCED         51329.793354
        MARRIED          58622.129444
        NEVER MARRIED    48763.820201
        SEPARATED        56198.865542
        WIDOWED          54918.039512
MALE    DIVORCED         62541.169549
        MARRIED          67658.692190
        NEVER MARRIED    50384.646330
        SEPARATED        60568.684286
        WIDOWED          66412.103434
Name: income, dtype: float64

#### **Unstack the Table**

In [89]:
multiple_grouping = df.groupby(['sex','marital'])['income'].mean().unstack()
multiple_grouping

marital      DIVORCED       MARRIED  NEVER MARRIED     SEPARATED       WIDOWED
sex
FEMALE   51329.793354  58622.129444   48763.820201  56198.865542  54918.039512
MALE     62541.169549  67658.692190   50384.646330  60568.684286  66412.103434

#### **Add More Categorical Variables**

In [90]:
print("Mean Income by Gender AND Marital Status")
multiple_grouping = df.groupby(['sex','marital', 'degree'])['income'].mean()
multiple_grouping

Mean Income by Gender AND Marital Status

sex     marital        degree
FEMALE  DIVORCED       BACHELOR           66000.005577
                       GRADUATE           96371.271389
                       HIGH SCHOOL        43432.538025
                       JUNIOR COLLEGE     61842.908214
                       LT HIGH SCHOOL     31164.281429
        MARRIED        BACHELOR           80891.451250
                       GRADUATE           98055.297368
                       HIGH SCHOOL        51643.596856
                       JUNIOR COLLEGE     58602.766563
                       LT HIGH SCHOOL     30986.332988
        NEVER MARRIED  BACHELOR           60106.639111
                       GRADUATE           92939.027414
                       HIGH SCHOOL        40957.714392
                       JUNIOR COLLEGE     52592.065991
                       LT HIGH SCHOOL     23940.274848
        SEPARATED      BACHELOR           71857.841458
                       GRADUATE           81795.057917
                       HIGH SCHOOL        47393.681389
                       JUNIOR COLLEGE     65039.558571
                       LT HIGH SCHOOL     35495.147500
        WIDOWED        BACHELOR           75323.098500
                       GRADUATE           91993.304000
                       HIGH SCHOOL        47278.949091
                       JUNIOR COLLEGE     76987.918375
                       LT HIGH SCHOOL     28914.174118
MALE    DIVORCED       BACHELOR           95417.128306
                       GRADUATE          100899.502500
                       HIGH SCHOOL        50543.274549
                       JUNIOR COLLEGE     65463.133088
                       LT HIGH SCHOOL     41513.139044
        MARRIED        BACHELOR           93975.251532
                       GRADUATE          114803.052627
                       HIGH SCHOOL        57758.371751
                       JUNIOR COLLEGE     75462.003140
                       LT HIGH SCHOOL     40606.823185
        NEVER MARRIED  BACHELOR           68866.653555
                       GRADUATE           91416.020375
                       HIGH SCHOOL        43045.164982
                       JUNIOR COLLEGE     56954.138472
                       LT HIGH SCHOOL     30194.801940
        SEPARATED      BACHELOR           86661.218750
                       GRADUATE          116461.833125
                       HIGH SCHOOL        52853.288500
                       JUNIOR COLLEGE     56911.043333
                       LT HIGH SCHOOL     37701.664615
        WIDOWED        BACHELOR          119482.447500
                       GRADUATE          111472.776667
                       HIGH SCHOOL        51566.073000
                       JUNIOR COLLEGE     69357.693333
                       LT HIGH SCHOOL     45447.369375
Name: income, dtype: float64

In [92]:
multiple_grouping = df.groupby(['sex','marital', 'degree'])['income'].mean().unstack()
multiple_grouping

degree                     BACHELOR       GRADUATE   HIGH SCHOOL  \
sex    marital
FEMALE DIVORCED        66000.005577   96371.271389  43432.538025
       MARRIED         80891.451250   98055.297368  51643.596856
       NEVER MARRIED   60106.639111   92939.027414  40957.714392
       SEPARATED       71857.841458   81795.057917  47393.681389
       WIDOWED         75323.098500   91993.304000  47278.949091
MALE   DIVORCED        95417.128306  100899.502500  50543.274549
       MARRIED         93975.251532  114803.052627  57758.371751
       NEVER MARRIED   68866.653555   91416.020375  43045.164982
       SEPARATED       86661.218750  116461.833125  52853.288500
       WIDOWED        119482.447500  111472.776667  51566.073000

degree                JUNIOR COLLEGE  LT HIGH SCHOOL
sex    marital
FEMALE DIVORCED         61842.908214    31164.281429
       MARRIED          58602.766563    30986.332988
       NEVER MARRIED    52592.065991    23940.274848
       SEPARATED        65039.558571    35495.147500
       WIDOWED          76987.918375    28914.174118
MALE   DIVORCED         65463.133088    41513.139044
       MARRIED          75462.003140    40606.823185
       NEVER MARRIED    56954.138472    30194.801940
       SEPARATED        56911.043333    37701.664615
       WIDOWED          69357.693333    45447.369375

### **Advanced Grouping and Multiple Aggregation**

In [95]:
summary = df.groupby('degree').agg({
    'income':['mean','median','std','count'],
    'age':'mean',
    'hrswrk' : 'mean'
})
summary

                       income                                        age  \
                         mean      median           std count       mean
degree
BACHELOR         79394.490040   74575.610  33731.809663   566  39.909894
GRADUATE        101312.290983  107071.185  35499.023670   234  41.461538
HIGH SCHOOL      50326.169965   46500.255  26245.455646  1152  43.368924
JUNIOR COLLEGE   63991.209984   56549.830  30427.157545   465  41.578495
LT HIGH SCHOOL   33619.183349   29257.000  20586.434422   583  42.248714

                   hrswrk
                     mean
degree
BACHELOR        42.867491
GRADUATE        43.615385
HIGH SCHOOL     40.647569
JUNIOR COLLEGE  40.406452
LT HIGH SCHOOL  34.716981

### **Mutating-Feature Engineering**

In [96]:
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1.0,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18.0,73.2,86.3,35.0
1,2.0,MALE,HIGH SCHOOL,36544.91,MARRIED,35.0,69.9,95.3,47.0
2,3.0,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28.0,70.1,60.9,16.0
3,4.0,FEMALE,GRADUATE,49586.54,MARRIED,43.0,61.9,76.0,44.0
4,5.0,MALE,HIGH SCHOOL,48899.47,MARRIED,48.0,65.8,58.9,44.0

In [97]:
median_income = df['income'].median()
median_income

49586.54

In [100]:
df['Income_Category'] = np.where(df['income'] >= median_income,
                                 'High Income', 'Low Income')
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk,Income_Category
0,1.0,MALE,HIGH SCHOOL,26722.56,NEVER MARRIED,18.0,73.2,86.3,35.0,Low Income
1,2.0,MALE,HIGH SCHOOL,36544.91,MARRIED,35.0,69.9,95.3,47.0,Low Income
2,3.0,FEMALE,HIGH SCHOOL,59587.14,DIVORCED,28.0,70.1,60.9,16.0,High Income
3,4.0,FEMALE,GRADUATE,49586.54,MARRIED,43.0,61.9,76.0,44.0,High Income
4,5.0,MALE,HIGH SCHOOL,48899.47,MARRIED,48.0,65.8,58.9,44.0,Low Income

In [101]:
df['Income_Category'].value_counts()

Income_Category
High Income    1617
Low Income     1383
Name: count, dtype: int64

#### **Verify the Grouping**

In [102]:
print("Verification - Median Income by Income Levels")
df.groupby('Income_Category')['income'].median()

Verification - Median Income by Income Levels

Income_Category
High Income    71801.05
Low Income     31959.51
Name: income, dtype: float64

#### **Alternative Verifcation Process**

In [103]:
df.groupby('Income_Category')['income'].describe()

,count,mean,std,min,25%,50%,75%,max
Income_Category,,,,,,,,
High Income,1617.0,81755.685039,30507.829681,49586.54,55490.23,71801.05,102358.26,138753.5975
Low Income,1383.0,31653.694201,10696.713196,3720.04,23167.80,31959.51,40462.67,49576.4800

In [105]:
df.drop(columns = 'id').describe()

              income          age       height       weight       hrswrk
count    3000.000000  3000.000000  3000.000000  3000.000000  3000.000000
mean    58658.667263    42.072333    67.400367    76.315633    40.108000
std     34324.748715    13.298623     3.640892    14.158958    11.627642
min      3720.040000    18.000000    58.100000    45.000000    13.000000
25%     33681.547500    33.000000    64.600000    66.300000    34.000000
50%     49586.540000    42.000000    67.200000    75.700000    41.000000
75%     75710.367500    51.000000    70.100000    85.200000    48.000000
max    138753.597500    78.000000    78.350000   113.550000    69.000000

### **Frequency for Categorical Variables**

In [106]:
df.describe(include = ['object','category'])

           sex       degree  marital Income_Category
count     3000         3000     3000            3000
unique       2            5        5               2
top     FEMALE  HIGH SCHOOL  MARRIED     High Income
freq      1563         1152     1584            1617